# Generated by Django 3.0 on 2020-03-30 18:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('content', '0019_auto_20200330_1100'),
    ]

    operations = [
        migrations.CreateModel(
            name='ThirdPartyDonation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service', models.CharField(help_text='Payment service that the user made the donation through', max_length=255, verbose_name='payment service')),
                ('amount', models.DecimalField(blank=True, decimal_places=2, help_text='Amount donated to the artist', max_digits=11, null=True, verbose_name='donation amount')),
                ('other', models.BooleanField(blank=True, help_text="Indicates that the user picked an 'other' payment amount", null=True, verbose_name='other')),
                ('donor', models.ForeignKey(blank=True, help_text='The user who made the donation', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='third_party_donations_made', to=settings.AUTH_USER_MODEL, verbose_name='donor')),
                ('recipient', models.ForeignKey(help_text='The artist who recieved the donation', limit_choices_to={'platform': 'Revibe'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='third_party_donations_received', to='content.Artist', verbose_name='recipient')),
            ],
            options={
                'verbose_name': 'third party donation',
                'verbose_name_plural': 'third party donations',
            },
        ),
    ]
