# Generated by Django 3.0 on 2019-12-16 02:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import music.model_exts
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.CharField(default=uuid.uuid4, editable=False, max_length=255, primary_key=True, serialize=False)),
                ('uri', models.CharField(default=uuid.uuid4, editable=False, max_length=255, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('image', models.FileField(blank=True, null=True, upload_to=music.model_exts.rename_image, verbose_name='Album Image')),
                ('platform', models.CharField(max_length=255)),
                ('type', models.CharField(blank=True, max_length=255, null=True)),
                ('date_added', models.DateTimeField(auto_now_add=True, null=True)),
                ('last_changed', models.DateTimeField(auto_now=True, null=True)),
                ('date_published', models.DateField(blank=True, default=django.utils.timezone.now, null=True)),
                ('is_displayed', models.BooleanField(blank=True, default=True)),
                ('is_deleted', models.BooleanField(blank=True, default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Artist',
            fields=[
                ('id', models.CharField(default=uuid.uuid4, editable=False, max_length=255, primary_key=True, serialize=False)),
                ('uri', models.CharField(default=uuid.uuid4, editable=False, max_length=255, unique=True)),
                ('name', models.CharField(max_length=255, verbose_name='Display Name')),
                ('image', models.FileField(blank=True, null=True, upload_to=music.model_exts.rename_image, verbose_name='Display Image')),
                ('platform', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Library',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Playlist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, null=True, verbose_name='Name')),
                ('is_public', models.BooleanField(blank=True, default=False)),
                ('date_created', models.DateField(auto_now_add=True, null=True)),
            ],
            options={
                'verbose_name': 'playlist',
                'verbose_name_plural': 'playlists',
            },
        ),
        migrations.CreateModel(
            name='Song',
            fields=[
                ('id', models.CharField(default=uuid.uuid4, editable=False, max_length=255, primary_key=True, serialize=False)),
                ('uri', models.CharField(default=uuid.uuid4, editable=False, max_length=255, unique=True, verbose_name='URI')),
                ('file', models.FileField(blank=True, null=True, upload_to=music.model_exts.rename_song, verbose_name='Song')),
                ('title', models.CharField(max_length=255, verbose_name='Name')),
                ('duration', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='Duration')),
                ('platform', models.CharField(max_length=255, null=True)),
                ('uploaded_date', models.DateField(auto_now_add=True, null=True)),
                ('last_changed', models.DateField(auto_now=True, null=True)),
                ('genre', models.CharField(blank=True, max_length=255, null=True)),
                ('is_explicit', models.BooleanField(blank=True, default=False)),
                ('is_displayed', models.BooleanField(blank=True, default=True)),
                ('is_deleted', models.BooleanField(blank=True, default=False)),
                ('album', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='music.Album')),
            ],
        ),
        migrations.CreateModel(
            name='SongContributor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contribution_type', models.CharField(max_length=255, null=True)),
                ('date_added', models.DateField(auto_now_add=True, null=True)),
                ('last_changed', models.DateField(auto_now=True, null=True)),
                ('primary_artist', models.BooleanField(blank=True, default=False)),
                ('artist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='artist_to_song', to='music.Artist')),
                ('song', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='song_to_artist', to='music.Song')),
            ],
        ),
        migrations.AddField(
            model_name='song',
            name='contributors',
            field=models.ManyToManyField(related_name='song_contributors', through='music.SongContributor', to='music.Artist'),
        ),
        migrations.AddField(
            model_name='song',
            name='uploaded_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='song_uploaded_by', to='music.Artist'),
        ),
        migrations.CreateModel(
            name='PlaylistSongs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_saved', models.DateTimeField(auto_now_add=True)),
                ('playlist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='playlist_to_song', to='music.Playlist')),
                ('song', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='song_to_playlist', to='music.Song')),
            ],
            options={
                'verbose_name': 'playlist song',
                'verbose_name_plural': 'playlist songs',
            },
        ),
        migrations.AddField(
            model_name='playlist',
            name='songs',
            field=models.ManyToManyField(related_name='playlist_songs', through='music.PlaylistSongs', to='music.Song'),
        ),
        migrations.AddField(
            model_name='playlist',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='LibrarySongs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_saved', models.DateTimeField(auto_now_add=True)),
                ('library', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='library_to_song', to='music.Library')),
                ('song', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='song_to_library', to='music.Song')),
            ],
            options={
                'verbose_name': 'library song',
                'verbose_name_plural': 'library songs',
            },
        ),
        migrations.AddField(
            model_name='library',
            name='songs',
            field=models.ManyToManyField(related_name='library_songs', through='music.LibrarySongs', to='music.Song'),
        ),
        migrations.AddField(
            model_name='library',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='AlbumContributor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contribution_type', models.CharField(max_length=255, null=True)),
                ('date_added', models.DateField(auto_now_add=True, null=True)),
                ('last_changed', models.DateField(auto_now=True, null=True)),
                ('primary_artist', models.BooleanField(blank=True, default=False)),
                ('album', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='album_to_artist', to='music.Album')),
                ('artist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='artist_to_album', to='music.Artist')),
            ],
        ),
        migrations.AddField(
            model_name='album',
            name='contributors',
            field=models.ManyToManyField(through='music.AlbumContributor', to='music.Artist'),
        ),
        migrations.AddField(
            model_name='album',
            name='uploaded_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='album_uploaded_by', to='music.Artist'),
        ),
    ]
