# Generated by Django 2.2.6 on 2019-11-25 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='image',
            field=models.FileField(null=True, upload_to='images/albums', verbose_name='Album Image'),
        ),
        migrations.AlterField(
            model_name='song',
            name='uploaded_date',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
