# Generated by Django 3.0 on 2020-02-05 17:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='library',
            options={'verbose_name': 'library', 'verbose_name_plural': 'libraries'},
        ),
    ]
