# Generated by Django 3.0 on 2020-03-26 17:11

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('music', '0002_auto_20200205_1120'),
    ]

    operations = [
        migrations.AddField(
            model_name='playlist',
            name='followers',
            field=models.ManyToManyField(help_text='Users following this playlist. Followers cannot edit a playlist', related_name='followed_playlists', to=settings.AUTH_USER_MODEL, verbose_name='followers'),
        ),
        migrations.AddField(
            model_name='playlist',
            name='revibe_curated',
            field=models.BooleanField(blank=True, default=False, help_text="Revibe-curated playlist. Must set 'is public' to True in order for this to be available", verbose_name='revibe curated'),
        ),
        migrations.AddField(
            model_name='playlist',
            name='show_on_browse',
            field=models.BooleanField(blank=True, default=False, help_text="Allow this playlist to display on the Browse page. If not checked, it will still be available in search or in a user's followed playlists", verbose_name='show on browse'),
        ),
    ]
