# Generated by Django 2.2.6 on 2019-11-14 23:28

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0002_album_uploaded_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='uri',
            field=models.UUIDField(default=uuid.uuid4, unique=True, verbose_name='URI'),
        ),
    ]
