# Generated by Django 2.2.6 on 2019-11-08 17:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0002_auto_20191106_1458'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='artist',
            name='manager',
        ),
    ]
