# Generated by Django 2.2.6 on 2019-11-08 21:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0003_remove_artist_manager'),
    ]

    operations = [
        migrations.RenameField(
            model_name='song',
            old_name='name',
            new_name='title',
        ),
    ]
