# Generated by Django 2.2.6 on 2019-11-08 21:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0004_auto_20191108_1510'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AlbumContributors',
            new_name='AlbumContributor',
        ),
        migrations.RenameModel(
            old_name='SongContributors',
            new_name='SongContributor',
        ),
    ]
