# Generated by Django 3.0 on 2019-12-05 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0005_playlist_date_created'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SongAnalysis',
        ),
        migrations.AlterModelOptions(
            name='librarysongs',
            options={'verbose_name': 'library song', 'verbose_name_plural': 'library songs'},
        ),
        migrations.AlterModelOptions(
            name='playlist',
            options={'verbose_name': 'playlist', 'verbose_name_plural': 'playlists'},
        ),
        migrations.AlterModelOptions(
            name='playlistsongs',
            options={'verbose_name': 'playlist song', 'verbose_name_plural': 'playlist songs'},
        ),
        migrations.AddField(
            model_name='albumcontributor',
            name='date_added',
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='albumcontributor',
            name='last_changed',
            field=models.DateField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='songcontributor',
            name='date_added',
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='songcontributor',
            name='last_changed',
            field=models.DateField(auto_now=True, null=True),
        ),
    ]
