# Generated by Django 2.2.6 on 2019-11-11 19:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0005_auto_20191108_1535'),
    ]

    operations = [
        migrations.AlterField(
            model_name='songcontributor',
            name='artist',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='artist_to_song', to='music.Artist'),
        ),
        migrations.AlterField(
            model_name='songcontributor',
            name='song',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='song_to_artist', to='music.Song'),
        ),
    ]
