# Generated by Django 3.0 on 2020-03-30 23:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0005_auto_20200326_1237'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playlist',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
