# Generated by Django 2.2.6 on 2019-11-15 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0005_song_genre'),
    ]

    operations = [
        migrations.CreateModel(
            name='SongAnalysis',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.AddField(
            model_name='album',
            name='type',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
