# Generated by Django 3.0 on 2019-12-05 22:01

from django.db import migrations, models
import music.model_exts
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0006_auto_20191205_1418'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='uri',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='URI'),
        ),
        migrations.AlterField(
            model_name='album',
            name='image',
            field=models.FileField(null=True, upload_to=music.model_exts.rename_image, verbose_name='Album Image'),
        ),
    ]
