# Generated by Django 3.0 on 2020-04-08 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0007_playlist_description'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='playlistsong',
            options={'ordering': ['order', '-date_saved'], 'verbose_name': 'playlist song', 'verbose_name_plural': 'playlist songs'},
        ),
        migrations.AddField(
            model_name='playlistsong',
            name='order',
            field=models.IntegerField(blank=True, default=0, help_text='Order to display the songs in. If multiple are equal, will order by date_saved', verbose_name='order'),
        ),
    ]
