# Generated by Django 3.0 on 2019-12-05 22:03

from django.db import migrations, models
import music.model_exts
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0007_auto_20191205_1601'),
    ]

    operations = [
        migrations.AddField(
            model_name='artist',
            name='uri',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='URI'),
        ),
        migrations.AlterField(
            model_name='artist',
            name='image',
            field=models.FileField(upload_to=music.model_exts.rename_image, verbose_name='Display Image'),
        ),
    ]
