# Generated by Django 3.0 on 2020-05-22 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0008_auto_20200408_1600'),
    ]

    operations = [
        migrations.AddField(
            model_name='playlist',
            name='last_changed',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
