# Generated by Django 3.0 on 2019-12-09 16:16

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0009_auto_20191209_1014'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='date_published',
            field=models.DateField(blank=True, default=django.utils.timezone.now, null=True),
        ),
    ]
