# Generated by Django 3.0 on 2019-12-11 17:02

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0010_auto_20191209_1016'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='id',
            field=models.CharField(default=uuid.uuid4, editable=False, max_length=255, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='song',
            name='uri',
            field=models.CharField(default=uuid.uuid4, editable=False, max_length=255, unique=True, verbose_name='URI'),
        ),
    ]
