# Generated by Django 3.0 on 2019-12-12 17:34

from django.db import migrations, models
import music.model_exts
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0011_auto_20191211_1102'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='last_changed',
            field=models.DateField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='album',
            name='id',
            field=models.CharField(default=uuid.uuid4, editable=False, max_length=255, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='album',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to=music.model_exts.rename_image, verbose_name='Album Image'),
        ),
        migrations.AlterField(
            model_name='album',
            name='uri',
            field=models.CharField(default=uuid.uuid4, editable=False, max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='artist',
            name='id',
            field=models.CharField(default=uuid.uuid4, editable=False, max_length=255, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='artist',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to=music.model_exts.rename_image, verbose_name='Display Image'),
        ),
        migrations.AlterField(
            model_name='artist',
            name='uri',
            field=models.CharField(default=uuid.uuid4, editable=False, max_length=255, unique=True),
        ),
    ]
