# Generated by Django 3.0 on 2019-12-12 18:24

from django.db import migrations, models
import music.model_exts


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0012_auto_20191212_1134'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to=music.model_exts.rename_song, verbose_name='Song'),
        ),
    ]
