# Generated by Django 3.0 on 2019-12-16 00:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0015_albumcontributor_primary_artist'),
    ]

    operations = [
        migrations.AddField(
            model_name='playlist',
            name='is_public',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AddField(
            model_name='song',
            name='is_explicit',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
