# Generated by Django 3.0 on 2019-12-31 17:35

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Campaign',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uri', models.CharField(default=uuid.uuid1, editable=False, max_length=255, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('budget', models.IntegerField()),
                ('spent', models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
