# Generated by Django 3.0 on 2020-01-08 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactform',
            name='email',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Email'),
        ),
        migrations.AddField(
            model_name='contactform',
            name='first_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='First Name'),
        ),
        migrations.AddField(
            model_name='contactform',
            name='last_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Last Name'),
        ),
        migrations.AlterField(
            model_name='contactform',
            name='assigned_to',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name="Revibe staff member it's assigned to"),
        ),
        migrations.AlterField(
            model_name='contactform',
            name='message',
            field=models.TextField(verbose_name='Message'),
        ),
        migrations.AlterField(
            model_name='contactform',
            name='resolved',
            field=models.BooleanField(default=False, verbose_name='Indicates if the request/issue has been resolved or not'),
        ),
        migrations.AlterField(
            model_name='contactform',
            name='subject',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Contact form subject / type of request'),
        ),
    ]
