# Generated by Django 3.0 on 2020-01-10 18:11

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0002_auto_20200108_0932'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campaign',
            name='uri',
            field=models.CharField(default=uuid.uuid1, max_length=255, unique=True),
        ),
    ]
