# Generated by Django 3.0 on 2020-01-12 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0003_auto_20200110_1211'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactform',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='When the form was submitted'),
        ),
        migrations.AddField(
            model_name='contactform',
            name='last_changed',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='Last time the form was edited'),
        ),
    ]
