# Generated by Django 3.0 on 2020-01-27 21:10

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0004_auto_20200112_0913'),
    ]

    operations = [
        migrations.CreateModel(
            name='YouTubeKey',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(help_text='API Key', max_length=255, unique=True)),
                ('last_tested', models.DateTimeField(blank=True, default=django.utils.timezone.now)),
                ('worked_on_last_test', models.BooleanField(blank=True, default=True, help_text='The last time this key was tested, it worked.')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'YouTube Key',
                'verbose_name_plural': 'YouTube Keys',
            },
        ),
    ]
