# Generated by Django 3.0 on 2020-01-27 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0005_youtubekey'),
    ]

    operations = [
        migrations.AddField(
            model_name='youtubekey',
            name='failure_count',
            field=models.IntegerField(blank=True, default=0, help_text='The number of failures without passing'),
        ),
    ]
