# Generated by Django 3.0 on 2020-02-03 15:07

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0006_youtubekey_failure_count'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='youtubekey',
            options={'ordering': ['-point_budget'], 'verbose_name': 'YouTube Key', 'verbose_name_plural': 'YouTube Keys'},
        ),
        migrations.AddField(
            model_name='youtubekey',
            name='number_of_users',
            field=models.IntegerField(blank=True, default=0, help_text='Estimated number of users using this key'),
        ),
        migrations.AddField(
            model_name='youtubekey',
            name='point_budget',
            field=models.IntegerField(blank=True, default=0, help_text='Number of points this API key is allotted'),
        ),
        migrations.AlterField(
            model_name='youtubekey',
            name='last_tested',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, help_text='Time the key was last tested against the YouTube servers'),
        ),
    ]
