# Generated by Django 3.0 on 2020-02-05 17:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion

def set_assignment_to_null(apps, schema_editor):
    forms = apps.get_model('administration','contactform')
    forms.objects.update(assigned_to=None)

class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('administration', '0007_auto_20200203_0907'),
    ]

    operations = [
        migrations.RunPython(set_assignment_to_null),
        migrations.AlterField(
            model_name='contactform',
            name='assigned_to',
            field=models.ForeignKey(blank=True, help_text="Revibe staff member it's assigned to", limit_choices_to={'is_staff': True}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contact_form_assignment', to=settings.AUTH_USER_MODEL, verbose_name='staff member'),
        ),
        migrations.AlterField(
            model_name='contactform',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, help_text='When the form was submitted', null=True),
        ),
        migrations.AlterField(
            model_name='contactform',
            name='resolved',
            field=models.BooleanField(default=False, help_text='Indicates if the request/issue has been resolved or not'),
        ),
    ]
