# Generated by Django 3.0 on 2020-02-10 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0010_campaign_destination'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campaign',
            name='destination',
            field=models.CharField(blank=True, choices=[('user', 'Listener'), ('artist', 'Artist'), ('other', 'Other')], help_text='Target audience', max_length=255, null=True),
        ),
    ]
