# Generated by Django 3.0 on 2020-02-25 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0012_auto_20200213_1126'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='youtubekey',
            name='failure_count',
        ),
        migrations.RemoveField(
            model_name='youtubekey',
            name='last_tested',
        ),
        migrations.RemoveField(
            model_name='youtubekey',
            name='worked_on_last_test',
        ),
        migrations.AddField(
            model_name='youtubekey',
            name='last_date_broken',
            field=models.DateField(blank=True, help_text='The last date that this key ran dry', null=True, verbose_name='Most recent date expired'),
        ),
    ]
