# Generated by Django 3.0 on 2020-02-28 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0013_auto_20200225_1646'),
    ]

    operations = [
        migrations.CreateModel(
            name='Alert',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(blank=True, help_text='The subject of the message to send', max_length=255, null=True, verbose_name='subject')),
                ('message', models.TextField(help_text='The content of the alert to send to users.', verbose_name='Message')),
                ('category', models.CharField(choices=[('warn', 'Warning'), ('error', 'Error'), ('info', 'Information'), ('feature', 'New Feature')], help_text='The type of alert to send to users', max_length=255, verbose_name='alert category')),
                ('start_date', models.DateTimeField(blank=True, help_text='The date to start sending the alert on', null=True, verbose_name='message start date')),
                ('end_date', models.DateTimeField(blank=True, help_text='The date to stop sending the alert on', null=True, verbose_name='message end date')),
                ('enabled', models.BooleanField(default=True, help_text='When set to off, will not be sent to any more users', verbose_name='Message is enabled')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'system alert',
                'verbose_name_plural': 'system alerts',
            },
        ),
    ]
