# Generated by Django 3.0 on 2020-03-02 22:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0016_artistspotlight'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='artistspotlight',
            options={'verbose_name': 'artist spotlight', 'verbose_name_plural': 'artist spotlights'},
        ),
    ]
