# Generated by Django 3.0 on 2020-03-16 17:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0018_auto_20200313_1354'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(help_text='subject of the post', max_length=255, verbose_name='subject')),
                ('body', models.TextField(help_text='body of the post', verbose_name='body')),
                ('publish_date', models.DateField(default=datetime.date.today, help_text='date that the post will go live', verbose_name='publish date')),
            ],
            options={
                'verbose_name': 'blog post',
                'verbose_name_plural': 'blog posts',
            },
        ),
    ]
