# Generated by Django 3.0 on 2020-03-16 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0019_blog'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='display_style',
            field=models.IntegerField(blank=True, choices=[(1, 'Style A'), (2, 'Style B')], default=1, help_text='Style to display the post in. See documentation for info', verbose_name='display style'),
        ),
        migrations.AddField(
            model_name='blog',
            name='header_image',
            field=models.FileField(blank=True, help_text='Image to be used at the top of the blog post', null=True, upload_to='', verbose_name='header image'),
        ),
        migrations.AddField(
            model_name='blog',
            name='side_image',
            field=models.FileField(blank=True, help_text='Image for the side of the blog post', upload_to='', verbose_name='side image'),
        ),
    ]
