# Generated by Django 3.0 on 2020-03-16 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0020_auto_20200316_1325'),
    ]

    operations = [
        migrations.CreateModel(
            name='Variable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(help_text='key of the key-value pair', max_length=255, unique=True, verbose_name='key')),
                ('value', models.TextField(help_text='value of the key-value pair', verbose_name='value')),
            ],
            options={
                'verbose_name': 'variable',
                'verbose_name_plural': 'variables',
            },
        ),
    ]
