# Generated by Django 3.0 on 2020-03-18 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0023_auto_20200318_1611'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='category',
            field=models.CharField(choices=[('artist_of_the_week', 'Artist of the Week'), ('education', 'Education'), ('playlist', 'Playlist'), ('other', 'Other')], default='FIX', help_text='Which blog this post belongs to', max_length=255, verbose_name='category'),
            preserve_default=False,
        ),
    ]
