# Generated by Django 3.0 on 2020-03-25 20:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('administration', '0025_auto_20200323_1418'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactform',
            name='assigned_to',
            field=models.ForeignKey(blank=True, help_text="Revibe staff member it's assigned to", limit_choices_to={'is_staff': True, 'programmatic_account': False}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contact_form_assignment', to=settings.AUTH_USER_MODEL, verbose_name='staff member'),
        ),
    ]
