# Generated by Django 3.0 on 2020-04-02 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0027_auto_20200331_1353'),
    ]

    operations = [
        migrations.AddField(
            model_name='variable',
            name='browse',
            field=models.BooleanField(default=False, help_text='Indicates that this variable is for the browse page. Simply makes filtering easier.', verbose_name='browse'),
        ),
    ]
