# Generated by Django 3.0 on 2020-04-16 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0028_variable_browse'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='variable',
            name='browse',
        ),
        migrations.AddField(
            model_name='variable',
            name='category',
            field=models.CharField(blank=True, choices=[('browse', 'Browse'), ('search', 'Search'), ('social', 'Social'), ('util', 'Utils')], help_text='Type of variable this is. Only used for sorting/filtering in the admin portal.', max_length=255, null=True, verbose_name='category'),
        ),
    ]
