# Generated by Django 3.0 on 2020-05-01 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0029_auto_20200416_1326'),
    ]

    operations = [
        migrations.AlterField(
            model_name='variable',
            name='category',
            field=models.CharField(blank=True, choices=[('artist-portal', 'Artist Portal Dashboard'), ('browse', 'Browse'), ('search', 'Search'), ('social', 'Social'), ('util', 'Utils')], help_text='Type of variable this is. Only used for sorting/filtering in the admin portal.', max_length=255, null=True, verbose_name='category'),
        ),
    ]
