# Generated by Django 3.0 on 2020-05-04 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0030_auto_20200501_1312'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArtistAnalyticsCalculation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='name')),
                ('lookup', models.CharField(help_text='The string to use when looking up the calculation field', max_length=255, verbose_name='lookup field')),
                ('_calculation', models.CharField(blank=True, choices=[('Avg', 'Average'), ('Max', 'Maximum'), ('Min', 'Minimum'), ('Count', 'Count'), ('Sum', 'Sum')], default='Count', help_text='The aggregation function to use', max_length=50, verbose_name='calculation')),
                ('distinct', models.BooleanField(blank=True, default=False, help_text='Should the aggregation function only look for distinct values?', verbose_name='distinct')),
                ('bar_name', models.CharField(blank=True, help_text="I honestly don't remember what this is here to do...", max_length=255, null=True, verbose_name='bar name')),
            ],
            options={
                'verbose_name': 'artist analytics calculation',
                'verbose_name_plural': 'artist analytics calculations',
            },
        ),
    ]
