# Generated by Django 3.0 on 2020-05-04 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0031_artistanalyticscalculation'),
    ]

    operations = [
        migrations.AddField(
            model_name='artistanalyticscalculation',
            name='root_object',
            field=models.CharField(choices=[('Album', 'Albums'), ('LibrarySong', 'Library'), ('PlaylistSong', 'Playlists'), ('Stream', 'Streams'), ('Song', 'Songs')], default='Stream', help_text='The root object for calculations', max_length=50, verbose_name='root object'),
            preserve_default=False,
        ),
    ]
