# Generated by Django 3.0 on 2020-05-05 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0032_artistanalyticscalculation_root_object'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artistanalyticscalculation',
            name='root_object',
            field=models.CharField(choices=[('albums', 'Albums'), ('librarysongs', 'Library'), ('playlistsongs', 'Playlists'), ('streams', 'Streams'), ('songs', 'Songs')], help_text='The root object for calculations', max_length=50, verbose_name='root object'),
        ),
    ]
