# Generated by Django 3.0 on 2020-05-05 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0033_auto_20200505_0935'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artistanalyticscalculation',
            name='root_object',
            field=models.CharField(choices=[('albums', 'Albums'), ('libraries', 'Library'), ('playlists', 'Playlists'), ('streams', 'Streams'), ('songs', 'Songs')], help_text='The root object for calculations', max_length=50, verbose_name='root object'),
        ),
    ]
