# Generated by Django 3.0 on 2020-05-05 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0034_auto_20200505_1034'),
    ]

    operations = [
        migrations.AddField(
            model_name='artistanalyticscalculation',
            name='notes',
            field=models.TextField(blank=True, help_text='Notes about this calculation', null=True, verbose_name='notes'),
        ),
    ]
