# Generated by Django 3.0 on 2020-05-06 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0036_auto_20200506_1025'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artistanalyticscalculation',
            name='root_object',
            field=models.CharField(choices=[('albums', 'Albums'), ('libraries', 'Library'), ('librarysongs', 'Library Songs'), ('playlists', 'Playlists'), ('playlistsongs', 'Playlist Songs'), ('streams', 'Streams'), ('songs', 'Songs')], help_text='The root object for calculations', max_length=50, verbose_name='root object'),
        ),
    ]
