# Generated by Django 3.0 on 2020-05-22 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0040_auto_20200519_1213'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactform',
            name='priority',
            field=models.CharField(blank=True, choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical'), ('emergency', 'Emergency')], help_text='Importance of the form, if applicable', max_length=100, null=True, verbose_name='priority'),
        ),
    ]
