# Generated by Django 3.0 on 2020-05-22 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0041_contactform_priority'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactform',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='contactform',
            name='last_changed',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
