# Generated by Django 3.0 on 2020-05-22 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0042_auto_20200522_1038'),
    ]

    operations = [
        migrations.AddField(
            model_name='artistspotlight',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='artistspotlight',
            name='last_changed',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
