# Generated by Django 3.0 on 2020-05-22 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0044_artistspotlight_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='last_changed',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
