# Generated by Django 3.0 on 2020-05-22 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0046_auto_20200522_1107'),
    ]

    operations = [
        migrations.AddField(
            model_name='alert',
            name='last_changed',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
