# Generated by Django 3.0 on 2020-05-22 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0047_alert_last_changed'),
    ]

    operations = [
        migrations.AddField(
            model_name='youtubekey',
            name='last_changed',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='alert',
            name='enabled',
            field=models.BooleanField(default=True, help_text='Enables/disables sending this alert', verbose_name='active'),
        ),
    ]
