# Generated by Django 3.0 on 2020-05-26 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0048_auto_20200522_1128'),
    ]

    operations = [
        migrations.AddField(
            model_name='variable',
            name='active',
            field=models.BooleanField(default=True, help_text='Enable/disable this variable.', verbose_name='active'),
        ),
        migrations.AddField(
            model_name='variable',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='variable',
            name='last_changed',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
