# Generated by Django 3.0 on 2020-05-28 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0049_auto_20200526_1323'),
    ]

    operations = [
        migrations.AlterField(
            model_name='survey',
            name='name',
            field=models.CharField(help_text='Name of the survey', max_length=255, verbose_name='name'),
        ),
    ]
