# Generated by Django 3.0 on 2020-06-10 17:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0028_search_order'),
        ('administration', '0052_auto_20200602_1123'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArtistOfTheWeek',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(help_text="When to start this artist's week. Will last for 7 days, including this one.", verbose_name='start date')),
                ('statement', models.TextField(blank=True, help_text='Statement/quote from the artist', null=True, verbose_name='statement')),
                ('active', models.BooleanField(default=True, help_text='Enables the object to be used in the apps', verbose_name='active')),
                ('description', models.TextField(blank=True, help_text='Human-readable information about this Artist of the Week', null=True, verbose_name='description')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('last_changed', models.DateTimeField(auto_now=True)),
                ('artist', models.ForeignKey(limit_choices_to={'platform', 'Revibe'}, on_delete=django.db.models.deletion.CASCADE, related_name='weeks', to='content.Artist', verbose_name='artist')),
                ('highlighted_album', models.ForeignKey(blank=True, help_text='An album the Artist would like to highlight for the week', limit_choices_to={'is_deleted': False}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='highlights', to='content.Album', verbose_name='highlighted album')),
            ],
        ),
    ]
