# Generated by Django 3.0 on 2020-06-15 20:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0029_image_artistoftheweek'),
        ('administration', '0053_artistoftheweek'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='artistoftheweek',
            options={'verbose_name': 'artist of the week', 'verbose_name_plural': 'artists of the week'},
        ),
        migrations.AlterField(
            model_name='artistoftheweek',
            name='artist',
            field=models.ForeignKey(limit_choices_to={'platform': 'Revibe'}, on_delete=django.db.models.deletion.CASCADE, related_name='weeks', to='content.Artist', verbose_name='artist'),
        ),
        migrations.AlterField(
            model_name='artistoftheweek',
            name='highlighted_album',
            field=models.ForeignKey(blank=True, help_text='An album the Artist would like to highlight for the week', limit_choices_to={'is_deleted': False, 'platform': 'Revibe'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='highlights', to='content.Album', verbose_name='highlighted album'),
        ),
    ]
