# Generated by Django 3.0 on 2020-06-03 17:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Referral',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('referree_ip_address', models.CharField(blank=True, help_text='The IP address of the referree. Used for scam prevention', max_length=255, null=True, verbose_name='referree IP address')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('referree', models.OneToOneField(help_text='The user that was referred', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='referal', to=settings.AUTH_USER_MODEL, verbose_name='referree')),
                ('referrer', models.ForeignKey(help_text='The user that did the referring', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='referalls', to=settings.AUTH_USER_MODEL, verbose_name='referrer')),
            ],
            options={
                'verbose_name': 'referral',
                'verbose_name_plural': 'referrals',
            },
        ),
    ]
