# Generated by Django 3.0 on 2020-06-03 18:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('referrals', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='referral',
            name='referree',
            field=models.OneToOneField(help_text='The user that was referred', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='referal', to=settings.AUTH_USER_MODEL, verbose_name='referred'),
        ),
        migrations.AlterField(
            model_name='referral',
            name='referrer',
            field=models.ForeignKey(help_text='The user that did the referring', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='referalls', to=settings.AUTH_USER_MODEL, verbose_name='sent'),
        ),
    ]
