# Generated by Django 3.0 on 2020-06-04 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('referrals', '0004_point_pointcategory'),
    ]

    operations = [
        migrations.AddField(
            model_name='pointcategory',
            name='repeating',
            field=models.BooleanField(default=False, help_text='Allow referring users to receive points for an action multiple times', verbose_name='repeating'),
        ),
    ]
