# Generated by Django 3.0 on 2020-06-04 18:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('referrals', '0005_pointcategory_repeating'),
    ]

    operations = [
        migrations.AddField(
            model_name='pointcategory',
            name='expiration_interval',
            field=models.CharField(blank=True, choices=[('days', 'Days')], help_text='Time period to use when expiring. Leave blank to not expire', max_length=100, null=True, verbose_name='expiration interval'),
        ),
        migrations.AddField(
            model_name='pointcategory',
            name='expiration_number_of_periods',
            field=models.IntegerField(blank=True, help_text='Number of expiration periods', null=True, verbose_name='number of periods'),
        ),
        migrations.AlterField(
            model_name='referral',
            name='referree',
            field=models.OneToOneField(help_text='The user that was referred', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='referral', to=settings.AUTH_USER_MODEL, verbose_name='referred'),
        ),
    ]
