# Generated by Django 3.0 on 2020-06-04 18:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('referrals', '0006_auto_20200604_1307'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='point',
            name='user',
        ),
        migrations.AddField(
            model_name='point',
            name='referral',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='points', to='referrals.Referral', verbose_name='referral'),
        ),
    ]
