# Generated by Django 3.0 on 2020-06-05 15:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('referrals', '0008_auto_20200605_0950'),
        ('referrals', '0008_auto_20200604_1503'),
    ]

    operations = [
    ]
