# Generated by Django 3.0 on 2020-03-20 18:26

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import revibe.contrib.models.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('content', '0016_auto_20200318_1110'),
    ]

    operations = [
        migrations.CreateModel(
            name='Good',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('product', 'Product'), ('service', 'Service')], help_text="Either a 'product' or 'service' offering", max_length=100, verbose_name='category')),
                ('name', models.CharField(help_text='Display name for the product or service', max_length=255, verbose_name='name')),
                ('description', models.TextField(blank=True, help_text='Item description', null=True, verbose_name='description')),
                ('image', models.FileField(blank=True, help_text='Image to display for this good', null=True, upload_to='', verbose_name='image')),
                ('audio', models.FileField(blank=True, help_text='Audio or audio sample for the good', null=True, upload_to='', verbose_name='audio')),
                ('price', models.DecimalField(decimal_places=2, help_text='The price of the product or service', max_digits=6, verbose_name='price')),
                ('discount', revibe.contrib.models.fields.IntegerRangeField(default=0, help_text='The percentage discount of the good', verbose_name='discount')),
                ('publish_date', models.DateField(blank=True, default=django.utils.timezone.now, help_text='Date the good will go public', verbose_name='publish date')),
                ('sold', models.BooleanField(default=False, help_text='Shows the item has been sold or not', verbose_name='sold status')),
                ('sale_date', models.DateTimeField(blank=True, help_text='The date and time the good was sold', null=True, verbose_name='sale date')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('last_changed', models.DateTimeField(auto_now=True)),
                ('purchaser', models.ForeignKey(blank=True, default=None, help_text='Purchaser of the good. Must be a Revibe artist', limit_choices_to={'platform': 'Revibe'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='purchased_goods', to='content.Artist', verbose_name='purchaser')),
                ('seller', models.ForeignKey(help_text='Seller of the good. Must be a Revibe artist', limit_choices_to={'platform': 'Revibe'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sale_goods', to='content.Artist', verbose_name='seller')),
            ],
            options={
                'verbose_name': 'good',
                'verbose_name_plural': 'goods',
            },
        ),
    ]
