# Generated by Django 3.0 on 2020-03-20 21:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0017_auto_20200320_1618'),
        ('marketplace', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='good',
            name='audio',
        ),
        migrations.RemoveField(
            model_name='good',
            name='image',
        ),
        migrations.RemoveField(
            model_name='good',
            name='purchaser',
        ),
        migrations.RemoveField(
            model_name='good',
            name='sale_date',
        ),
        migrations.RemoveField(
            model_name='good',
            name='sold',
        ),
        migrations.AddField(
            model_name='good',
            name='available',
            field=models.BooleanField(blank=True, default=True, help_text='The item is currently available for sale', verbose_name='available'),
        ),
        migrations.AddField(
            model_name='good',
            name='repeating',
            field=models.BooleanField(blank=True, default=False, help_text='The item is not limited to one purchase', verbose_name='repeating'),
        ),
        migrations.AlterField(
            model_name='good',
            name='price',
            field=models.DecimalField(decimal_places=2, help_text='The price of the product or service', max_digits=11, verbose_name='price'),
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('posted_price', models.DecimalField(decimal_places=2, help_text='The listing price (including discounts) at the time of the transaction', max_digits=11, verbose_name='posted price')),
                ('sale_price', models.DecimalField(decimal_places=2, help_text='The amount actually paid', max_digits=11, verbose_name='sale price')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('buyer', models.ForeignKey(help_text='Artist who bought the good', limit_choices_to={'platform': 'Revibe'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='content.Artist', verbose_name='buyer')),
                ('good', models.ForeignKey(help_text='Marketplace item', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='marketplace.Good', verbose_name='good')),
            ],
        ),
    ]
