# Generated by Django 3.0 on 2020-03-20 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0002_auto_20200320_1618'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='returned',
            field=models.BooleanField(blank=True, default=False, help_text='The purchase was returned and refunded', verbose_name='returned'),
        ),
    ]
