# Generated by Django 3.0 on 2020-03-23 19:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0003_transaction_returned'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='transaction',
            options={'verbose_name': 'transaction', 'verbose_name_plural': 'transactions'},
        ),
    ]
