# Generated by Django 3.0 on 2019-12-19 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='artistprofile',
            name='about_me',
            field=models.TextField(blank=True, null=True),
        ),
    ]
