# Generated by Django 2.2.6 on 2019-11-05 22:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20191105_2114'),
    ]

    operations = [
        migrations.AlterField(
            model_name='social',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_social', to=settings.AUTH_USER_MODEL),
        ),
    ]
