# Generated by Django 2.2.6 on 2019-11-03 23:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20191103_1603'),
    ]

    operations = [
        migrations.RenameField(
            model_name='social',
            old_name='paltform',
            new_name='platform',
        ),
    ]
