# Generated by Django 3.0 on 2019-12-19 20:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.OAUTH2_PROVIDER_ACCESS_TOKEN_MODEL),
        ('accounts', '0002_artistprofile_about_me'),
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_id', models.CharField(max_length=255, null=True)),
                ('device_type', models.CharField(choices=[('phone', 'Phone'), ('desktop', 'Desktop'), ('browser', 'Web Browser')], max_length=255, null=True)),
                ('device_name', models.CharField(max_length=255, null=True)),
                ('token', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.OAUTH2_PROVIDER_ACCESS_TOKEN_MODEL)),
            ],
        ),
    ]
