# Generated by Django 3.0 on 2019-12-16 22:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0001_initial'),
        ('accounts', '0003_auto_20191216_1210'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='allow_explicit',
            field=models.BooleanField(blank=True, default=True),
        ),
        migrations.CreateModel(
            name='ArtistProfile',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('require_contribution_approval', models.BooleanField(blank=True, default=True)),
                ('artist', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='music.Artist')),
            ],
        ),
    ]
