# Generated by Django 3.0 on 2020-01-09 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_artistprofile_require_contribution_approval_on_edit'),
    ]

    operations = [
        migrations.AddField(
            model_name='artistprofile',
            name='hide_all_content',
            field=models.BooleanField(blank=True, default=False, verbose_name="Hide all artist's content from appearing in the Revibe app, and prevents the artist from being added as a contributor."),
        ),
    ]
