# Generated by Django 3.0 on 2020-01-12 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_profile_campaign'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artistprofile',
            name='allow_contributors_to_edit_contributions',
            field=models.BooleanField(blank=True, default=False, verbose_name='Allow contributors to edit their contributions to content'),
        ),
        migrations.AlterField(
            model_name='artistprofile',
            name='require_contribution_approval',
            field=models.BooleanField(blank=True, default=True, verbose_name='Require that all new contributions must be approved by the artist'),
        ),
        migrations.AlterField(
            model_name='artistprofile',
            name='require_contribution_approval_on_edit',
            field=models.BooleanField(blank=True, default=True, verbose_name='Require that all changes to contributions must be re-approved by the artist'),
        ),
        migrations.AlterField(
            model_name='artistprofile',
            name='share_advanced_data_with_contributors',
            field=models.BooleanField(blank=True, default=False, verbose_name='Allow advanced streaming data to be shared with contributors to uploaded content'),
        ),
        migrations.AlterField(
            model_name='artistprofile',
            name='share_data_with_contributors',
            field=models.BooleanField(blank=True, default=True, verbose_name='Allow streaming data to be shared with contributors to uploaded content'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='is_artist',
            field=models.BooleanField(blank=True, default=False, verbose_name='Flag that indicates this user has an Artist Profile'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='is_manager',
            field=models.BooleanField(blank=True, default=False, verbose_name='Flag that indicates this user is a manager of an artist'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='allow_email_marketing',
            field=models.BooleanField(blank=True, default=True, verbose_name='Allow Revibe to send email to the user for marketing purposes'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='allow_explicit',
            field=models.BooleanField(blank=True, default=True, verbose_name='Allow the user to listen to explicit content'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='allow_listening_data',
            field=models.BooleanField(blank=True, default=True, verbose_name='Allow this user to be linked to the recorded listening data'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='email',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True, verbose_name="User's email address"),
        ),
    ]
