# Generated by Django 3.0 on 2019-12-27 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_auto_20191221_1729'),
    ]

    operations = [
        migrations.AddField(
            model_name='artistprofile',
            name='share_advanced_data_with_contributors',
            field=models.BooleanField(blank=True, default=True),
        ),
        migrations.AddField(
            model_name='artistprofile',
            name='share_data_with_contributors',
            field=models.BooleanField(blank=True, default=True),
        ),
    ]
