# Generated by Django 3.0 on 2020-01-15 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_auto_20200112_0913'),
    ]

    operations = [
        migrations.AddField(
            model_name='artistprofile',
            name='display_other_platform_content_on_revibe_page',
            field=models.BooleanField(blank=True, default=False, help_text="Display Spotify/YouTube content on the artist's Revibe artist page"),
        ),
        migrations.AddField(
            model_name='profile',
            name='skip_youtube_when_phone_is_locked',
            field=models.BooleanField(blank=True, default=True, help_text='Skip YouTube content while phone is locked'),
        ),
        migrations.AlterField(
            model_name='artistprofile',
            name='allow_contributors_to_edit_contributions',
            field=models.BooleanField(blank=True, default=False, help_text='Allow contributors to edit their contributions to content'),
        ),
        migrations.AlterField(
            model_name='artistprofile',
            name='hide_all_content',
            field=models.BooleanField(blank=True, default=False, help_text="Hide all artist's content from appearing in the Revibe app, and prevents the artist from being added as a contributor."),
        ),
        migrations.AlterField(
            model_name='artistprofile',
            name='require_contribution_approval',
            field=models.BooleanField(blank=True, default=True, help_text='Require that all new contributions must be approved by the artist'),
        ),
        migrations.AlterField(
            model_name='artistprofile',
            name='require_contribution_approval_on_edit',
            field=models.BooleanField(blank=True, default=True, help_text='Require that all changes to contributions must be re-approved by the artist'),
        ),
        migrations.AlterField(
            model_name='artistprofile',
            name='share_advanced_data_with_contributors',
            field=models.BooleanField(blank=True, default=False, help_text='Allow advanced streaming data to be shared with contributors to uploaded content'),
        ),
        migrations.AlterField(
            model_name='artistprofile',
            name='share_data_with_contributors',
            field=models.BooleanField(blank=True, default=True, help_text='Allow streaming data to be shared with contributors to uploaded content'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='allow_email_marketing',
            field=models.BooleanField(blank=True, default=True, help_text='Allow Revibe to send email to the user for marketing purposes'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='allow_explicit',
            field=models.BooleanField(blank=True, default=True, help_text='Allow the user to listen to explicit content'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='allow_listening_data',
            field=models.BooleanField(blank=True, default=True, help_text='Allow this user to be linked to the recorded listening data'),
        ),
    ]
