# Generated by Django 3.0 on 2020-01-15 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_auto_20200115_1530'),
    ]

    operations = [
        migrations.AddField(
            model_name='artistprofile',
            name='state',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
