# Generated by Django 3.0 on 2019-12-27 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_auto_20191227_1410'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artistprofile',
            name='share_advanced_data_with_contributors',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
