# Generated by Django 3.0 on 2020-01-21 03:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_artistprofile_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='is_artist',
            field=models.BooleanField(blank=True, default=False, help_text='Flag that indicates this user has an Artist Profile'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='is_manager',
            field=models.BooleanField(blank=True, default=False, help_text='Flag that indicates this user is a manager of an artist'),
        ),
    ]
