# Generated by Django 3.0 on 2019-12-27 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_auto_20191227_1412'),
    ]

    operations = [
        migrations.AddField(
            model_name='artistprofile',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
