# Generated by Django 3.0 on 2019-12-28 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_artistprofile_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='allow_email_marketing',
            field=models.BooleanField(blank=True, default=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='allow_listening_data',
            field=models.BooleanField(blank=True, default=True),
        ),
    ]
