# Generated by Django 3.0 on 2019-12-30 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_auto_20191228_0939'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artistprofile',
            name='email',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
