# Generated by Django 3.0 on 2020-02-05 18:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0008_auto_20200205_1120'),
        ('accounts', '0011_profile_referrer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='campaign',
            field=models.ForeignKey(blank=True, default=None, help_text='The marketing campaign that got this user', null=True, on_delete=django.db.models.deletion.SET_NULL, to='administration.Campaign', verbose_name='marketing campaign'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='email',
            field=models.CharField(blank=True, help_text="User's email address", max_length=255, null=True, unique=True),
        ),
    ]
