# Generated by Django 3.0 on 2020-02-10 19:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_auto_20200205_1233'),
    ]

    operations = [
        migrations.CreateModel(
            name='SocialMedia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service', models.CharField(default='other', help_text='Social media service - Twitter, Instagram, etc.', max_length=255)),
                ('description', models.CharField(blank=True, help_text='If service is other, this will be the displayed value for the link', max_length=255, null=True)),
                ('handle', models.CharField(help_text='Social media handle or URL', max_length=255)),
                ('artist_profile', models.ForeignKey(help_text="Account's artist", on_delete=django.db.models.deletion.CASCADE, to='accounts.ArtistProfile')),
            ],
        ),
    ]
