# Generated by Django 3.0 on 2020-02-10 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_auto_20200210_1351'),
    ]

    operations = [
        migrations.AlterField(
            model_name='socialmedia',
            name='service',
            field=models.CharField(choices=[('facebook', 'Facebook'), ('instagram', 'Instagram'), ('soundcloud', 'SoundCloud'), ('twitter', 'Twitter'), ('youtube', 'YouTube'), ('other', 'Other')], default='other', help_text='Social media service - Twitter, Instagram, etc.', max_length=255),
        ),
    ]
