# Generated by Django 3.0 on 2020-02-17 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_auto_20200210_1404'),
    ]

    operations = [
        migrations.AddField(
            model_name='artistprofile',
            name='allow_contributors_to_edit_tags',
            field=models.BooleanField(blank=True, default=False, help_text='Allows contributors to content to add/remove tags from that content'),
        ),
    ]
