# Generated by Django 3.0 on 2020-03-05 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0016_artistprofile_allow_contributors_to_edit_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='force_change_password',
            field=models.BooleanField(blank=True, default=False, help_text='User must change password on login', verbose_name='force change password'),
        ),
    ]
