# Generated by Django 3.0 on 2020-03-06 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0017_customuser_force_change_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='log_in_artist_portal',
            field=models.BooleanField(blank=True, default=False, help_text='Indicates if the user has logged in to the artist portal before/', verbose_name='logged in to Revibe Artist Portal'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='log_in_mobile_app',
            field=models.BooleanField(blank=True, default=False, help_text='Indicates if the user has logged in to the mobile app before', verbose_name='logged in to Revibe Music mobile'),
        ),
    ]
