# Generated by Django 3.0 on 2020-03-12 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0018_auto_20200306_1414'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='programmatic_account',
            field=models.BooleanField(blank=True, default=False, help_text='Programmatic accounts cannot login by normal means, they can only have access token generated for use in supplemental applications', verbose_name='programmatic account'),
        ),
    ]
