# Generated by Django 3.0 on 2020-03-30 16:52

from django.db import migrations, models


def include_venmo_and_cashapp(apps, schema_editor):
    """
    finds where 'venmo' or 'cashapp' may be in the social links,
    and converts them to official links and shit
    """
    social_media = apps.get_model('accounts', 'SocialMedia')
    medias = social_media.objects.filter(description__in=['venmo', 'cashapp', 'cash app'])
    for media in medias:
        new_service = str(media.description).lower().replace(" ", "")
        media.description = None
        media.service = new_service
        media.save()


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0020_auto_20200312_1108'),
    ]

    operations = [
        migrations.AlterField(
            model_name='socialmedia',
            name='service',
            field=models.CharField(choices=[('facebook', 'Facebook'), ('instagram', 'Instagram'), ('soundcloud', 'SoundCloud'), ('twitter', 'Twitter'), ('youtube', 'YouTube'), ('venmo', 'Venmo'), ('cashapp', 'Cash App'), ('other', 'Other')], default='other', help_text='Social media service - Twitter, Instagram, etc.', max_length=255),
        ),
        migrations.RunPython(include_venmo_and_cashapp),
    ]
