# Generated by Django 3.0 on 2020-03-30 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0021_auto_20200330_1152'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='allow_donation_data',
            field=models.BooleanField(blank=True, default=True, help_text="Determines if the user's donations will be recorded with their user", verbose_name='allow recording donation data'),
        ),
    ]
