# Generated by Django 3.0 on 2020-03-30 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0022_profile_allow_donation_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='artistprofile',
            name='allow_revibe_website_page',
            field=models.BooleanField(blank=True, default=False, help_text='Determines if the artist has a publicly available page on Revibe.tech', verbose_name='allow revibe website page'),
        ),
        migrations.AddField(
            model_name='artistprofile',
            name='public_url',
            field=models.CharField(blank=True, help_text="The url string to this artist's page in Revibe.tech", max_length=100, null=True, verbose_name='public url'),
        ),
    ]
