# Generated by Django 3.0 on 2020-03-30 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0023_auto_20200330_1417'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artistprofile',
            name='public_url',
            field=models.CharField(blank=True, help_text="The url string to this artist's page in Revibe.tech", max_length=100, null=True, unique=True, verbose_name='public url'),
        ),
    ]
