# Generated by Django 3.0 on 2020-04-02 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0024_auto_20200330_1441'),
    ]

    operations = [
        migrations.AddField(
            model_name='socialmedia',
            name='order',
            field=models.IntegerField(blank=True, help_text='The order to display the links in, if any', null=True, verbose_name='order'),
        ),
    ]
