# Generated by Django 3.0 on 2020-04-02 23:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0025_socialmedia_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='socialmedia',
            name='service',
            field=models.CharField(choices=[('facebook', 'Facebook'), ('instagram', 'Instagram'), ('twitter', 'Twitter'), ('spotify', 'Spotify'), ('applemusic', 'Apple Music'), ('amazonmusic', 'Amazon Music'), ('youtube', 'YouTube'), ('soundcloud', 'SoundCloud'), ('tidal', 'Tidal'), ('googleplaymusic', 'Google Play Music'), ('venmo', 'Venmo'), ('cashapp', 'Cash App'), ('other', 'Other')], default='other', help_text='Social media service - Twitter, Instagram, etc.', max_length=255),
        ),
    ]
