# Generated by Django 3.0 on 2020-04-14 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0027_auto_20200407_1928'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='allow_search_data',
            field=models.BooleanField(blank=True, default=True, help_text='Allow this user to be linked the recorded search data', verbose_name='allow search data'),
        ),
    ]
