# Generated by Django 3.0 on 2020-04-16 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0028_profile_allow_search_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='temporary_account',
            field=models.BooleanField(blank=True, default=False, help_text='Temporary accounts are people who have downloaded the app but have not yet fully registered for an account.', verbose_name='temporary account'),
        ),
    ]
