# Generated by Django 3.0 on 2020-04-28 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0029_customuser_temporary_account'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='date_registered',
            field=models.DateTimeField(blank=True, help_text='The datetime the user claimed their account', null=True, verbose_name='date registered'),
        ),
    ]
