# Generated by Django 3.0 on 2020-05-06 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0031_staffprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='allow_email_notifications',
            field=models.BooleanField(blank=True, default=True, help_text='Allow notifications to be sent by email', verbose_name='allow email notifications'),
        ),
        migrations.AddField(
            model_name='profile',
            name='allow_email_reminders',
            field=models.BooleanField(blank=True, default=True, help_text='Allow reminders sent by email', verbose_name='allow email reminders'),
        ),
    ]
