# Generated by Django 3.0 on 2020-05-13 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0032_auto_20200506_1626'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='allow_in_app_notifications',
            field=models.BooleanField(blank=True, default=True, help_text='Allow notifications to be sent in Revibe applications', verbose_name='allow in-app notifications'),
        ),
        migrations.AddField(
            model_name='profile',
            name='allow_push_notifications',
            field=models.BooleanField(blank=True, default=True, help_text="Allow push notifications to be sent to the user's device", verbose_name='allow pushy notifications'),
        ),
        migrations.AddField(
            model_name='profile',
            name='allow_sms_notifications',
            field=models.BooleanField(blank=True, default=True, help_text='Allow notifications to be sent by sms', verbose_name='allow sms notifications'),
        ),
    ]
