# Generated by Django 3.0 on 2020-02-25 23:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('content', '0013_song_streams_all_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stream',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('stream_duration', models.DecimalField(blank=True, decimal_places=2, help_text='The length of time the user streamed the song for', max_digits=4, null=True, verbose_name='stream duration')),
                ('is_downloaded', models.BooleanField(blank=True, help_text='Whether or not the user has the song downloaded', null=True, verbose_name='download status')),
                ('is_saved', models.BooleanField(blank=True, help_text='Whether or not the user has the song saved in their library at the time of streaming the song', null=True, verbose_name='saved status')),
                ('song', models.ForeignKey(help_text='The song that was streamed', on_delete=django.db.models.deletion.CASCADE, related_name='streams', to='content.Song', verbose_name='song')),
                ('user', models.ForeignKey(blank=True, help_text='The user that streamed the song', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='streams', to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
            options={
                'verbose_name': 'stream',
                'verbose_name_plural': 'streams',
            },
        ),
    ]
