# Generated by Django 3.0 on 2020-02-25 23:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metrics', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stream',
            name='stream_duration',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='The length of time the user streamed the song for', max_digits=8, null=True, verbose_name='stream duration'),
        ),
    ]
