# Generated by Django 3.0 on 2020-03-02 22:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('metrics', '0003_search'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppSession',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField(auto_now_add=True)),
                ('end_time', models.DateTimeField(auto_now=True)),
                ('interactions', models.IntegerField(blank=True, default=0, help_text='Number of interactions the user had with the app during the session', verbose_name='interactions')),
                ('user', models.ForeignKey(help_text='User that sessioned', on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
            options={
                'verbose_name': 'mobile app session',
                'verbose_name_plural': 'mobile app sessions',
            },
        ),
    ]
