# Generated by Django 3.0 on 2020-03-03 20:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0014_auto_20200226_1026'),
        ('metrics', '0004_appsession'),
    ]

    operations = [
        migrations.AddField(
            model_name='stream',
            name='alternate_id',
            field=models.CharField(blank=True, default=None, help_text='ID of the song/video streamed if that ID has not yet been stored in the database', max_length=255, null=True, verbose_name='alternate ID'),
        ),
        migrations.AddField(
            model_name='stream',
            name='alternate_platform',
            field=models.CharField(blank=True, default=None, help_text='Platform of the song/video if that song/video has not yet been stored in the database', max_length=255, null=True, verbose_name='alternate platform'),
        ),
        migrations.AlterField(
            model_name='stream',
            name='song',
            field=models.ForeignKey(blank=True, help_text='The song that was streamed', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='streams', to='content.Song', verbose_name='song'),
        ),
    ]
