# Generated by Django 3.0 on 2020-03-03 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metrics', '0005_auto_20200303_1403'),
    ]

    operations = [
        migrations.AddField(
            model_name='stream',
            name='lat',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='latitude'),
        ),
        migrations.AddField(
            model_name='stream',
            name='long',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='longitude'),
        ),
        migrations.AddField(
            model_name='stream',
            name='source',
            field=models.CharField(blank=True, choices=[('library', 'Library'), ('playlist', 'Playlist'), ('search', 'Search'), ('browse', 'Browse'), ('album', 'Album Page'), ('artist', 'Artist Page'), ('share', 'Shared'), ('embedded', 'Embedded Player')], help_text='Source the user streamed the song from: playlist, search, etc.', max_length=255, null=True, verbose_name='stream source'),
        ),
    ]
