# Generated by Django 3.0 on 2020-04-01 19:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0019_auto_20200330_1100'),
        ('metrics', '0007_artistpublicurlclicks'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ArtistPublicURLClicks',
            new_name='ArtistPublicURLClick',
        ),
    ]
