# Generated by Django 3.0 on 2020-05-20 16:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('notifications', '0012_auto_20200514_1057'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Action',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Human-readable name for this action', max_length=255, verbose_name='name')),
                ('interval_period', models.CharField(blank=True, choices=[('minutes', 'Minute(s)'), ('hours', 'Hour(s)'), ('days', 'Day(s)')], help_text='The type of period to use for time filtering', max_length=50, null=True, verbose_name='time period')),
                ('number_of_period', models.IntegerField(blank=True, default=1, help_text='Number of interval periods to use for time filtering', verbose_name='number of periods')),
                ('active', models.BooleanField(blank=True, default=True, help_text='Enable/disable this action', verbose_name='active')),
                ('description', models.TextField(blank=True, help_text='Description of the action', null=True, verbose_name='description')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('last_changed', models.DateTimeField(auto_now=True)),
                ('event', models.ForeignKey(blank=True, help_text='Denote which notifications to look for when recording notification attribution', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='actions', to='notifications.Event', verbose_name='event')),
            ],
        ),
        migrations.CreateModel(
            name='Pathway',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Human-readable name for the pathway', max_length=255, verbose_name='name')),
                ('description', models.TextField(blank=True, help_text='Human-readable description for the pathway', null=True, verbose_name='description')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('last_changed', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='PathwayAction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ranking', models.CharField(choices=[('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced'), ('special', 'Special'), ('other', 'Other')], help_text='The group in which this action resides in this pathway', max_length=100, verbose_name='ranking')),
                ('active', models.BooleanField(blank=True, default=True, help_text='Enable/Disable this relationship', verbose_name='active')),
                ('description', models.TextField(blank=True, help_text='Human-readable description for this relationship', null=True, verbose_name='description')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('last_changed', models.DateTimeField(auto_now=True)),
                ('action', models.ForeignKey(help_text='The action this pathway is related to', on_delete=django.db.models.deletion.CASCADE, related_name='pathwayactions', to='customer_success.Action', verbose_name='action')),
                ('pathway', models.ForeignKey(help_text='The pathway this action is related to', on_delete=django.db.models.deletion.CASCADE, related_name='pathwayactions', to='customer_success.Pathway', verbose_name='pathway')),
            ],
        ),
        migrations.CreateModel(
            name='ActionTaken',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('action', models.ForeignKey(help_text='The action taken', on_delete=django.db.models.deletion.CASCADE, related_name='actions_taken', to='customer_success.Action', verbose_name='action')),
                ('notification', models.ForeignKey(blank=True, help_text='The notification that triggered the user to take the action', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='actions_taken', to='notifications.Notification', verbose_name='notification')),
                ('user', models.ForeignKey(help_text='The user that did something', on_delete=django.db.models.deletion.CASCADE, related_name='actions_taken', to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
        ),
        migrations.AddField(
            model_name='action',
            name='pathways',
            field=models.ManyToManyField(blank=True, help_text='Pathways in which this action is included', related_name='actions', through='customer_success.PathwayAction', to='customer_success.Pathway', verbose_name='pathways'),
        ),
    ]
