# Generated by Django 3.0 on 2020-05-20 16:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0014_externalevent'),
        ('customer_success', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='action',
            name='event',
            field=models.ForeignKey(blank=True, help_text='Denote which notifications to look for when recording notification attribution', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='actions', to='notifications.TemporalEvent', verbose_name='event'),
        ),
    ]
