# Generated by Django 3.0 on 2020-05-20 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0014_externalevent'),
        ('customer_success', '0002_auto_20200520_1148'),
    ]

    operations = [
        migrations.AddField(
            model_name='action',
            name='extra_events',
            field=models.ManyToManyField(blank=True, help_text='Additional, attribution-only events. These are External Events that prompt the user to perform this action.', related_name='extra_actions', to='notifications.ExternalEvent', verbose_name='extra events'),
        ),
    ]
