# Generated by Django 3.0 on 2020-05-21 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer_success', '0004_auto_20200520_1317'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='action',
            options={'ordering': ['name'], 'verbose_name': 'action', 'verbose_name_plural': 'actions'},
        ),
        migrations.AlterModelOptions(
            name='pathway',
            options={'ordering': ['name'], 'verbose_name': 'path', 'verbose_name_plural': 'paths'},
        ),
        migrations.AlterField(
            model_name='pathway',
            name='description',
            field=models.TextField(blank=True, help_text='Human-readable description for the path', null=True, verbose_name='description'),
        ),
        migrations.AlterField(
            model_name='pathway',
            name='name',
            field=models.CharField(help_text='Human-readable name for the path', max_length=255, verbose_name='name'),
        ),
    ]
