# Generated by Django 3.0 on 2020-05-21 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer_success', '0005_auto_20200521_1245'),
    ]

    operations = [
        migrations.AddField(
            model_name='pathway',
            name='default',
            field=models.BooleanField(default=False, help_text='Denotes if this path is a default path for this user group.', verbose_name='default'),
        ),
        migrations.AddField(
            model_name='pathway',
            name='type',
            field=models.CharField(choices=[('artist', 'Artist'), ('listener', 'Listener')], default='listener', help_text='The user group that this pathway is designed for.', max_length=100, verbose_name='type'),
            preserve_default=False,
        ),
    ]
