# Generated by Django 3.0 on 2020-05-22 15:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer_success', '0007_pathway_users'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='actiontaken',
            options={'verbose_name': 'action taken', 'verbose_name_plural': 'actions taken'},
        ),
    ]
