# Generated by Django 3.0 on 2020-05-27 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer_success', '0008_auto_20200522_1000'),
    ]

    operations = [
        migrations.AddField(
            model_name='action',
            name='required_request_params_kwargs',
            field=models.TextField(default='{}', help_text='Keyword arguments that must evaluate to True when checked against the request parameter arguments. Must use JSON encoding.', verbose_name='request param kwargs'),
        ),
        migrations.AddField(
            model_name='action',
            name='required_response_body_kwargs',
            field=models.TextField(default='{}', help_text='Keywork arguments that must evaluate to True when checked against the response body. Must use JSON encoding.', verbose_name='response kwargs'),
        ),
    ]
