# Generated by Django 3.0 on 2020-05-28 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer_success', '0010_action_required_request_body_kwargs'),
    ]

    operations = [
        migrations.AddField(
            model_name='pathway',
            name='advanced_quota',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True, verbose_name='advanced quota'),
        ),
        migrations.AddField(
            model_name='pathway',
            name='beginner_quota',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True, verbose_name='beginner_quote'),
        ),
        migrations.AddField(
            model_name='pathway',
            name='intermediate_quota',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True, verbose_name='intermediate quota'),
        ),
        migrations.AddField(
            model_name='pathway',
            name='other_quota',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True, verbose_name='other quota'),
        ),
        migrations.AddField(
            model_name='pathway',
            name='special_quota',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True, verbose_name='special quota'),
        ),
    ]
