# Generated by Django 3.0 on 2020-05-28 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer_success', '0011_auto_20200528_1411'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pathway',
            name='beginner_quota',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True, verbose_name='beginner quota'),
        ),
    ]
