# Generated by Django 3.0 on 2020-05-29 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer_success', '0013_auto_20200529_1032'),
    ]

    operations = [
        migrations.AddField(
            model_name='pathwayaction',
            name='allow_recurrence',
            field=models.BooleanField(default=False, help_text='Allow action recurrence in this path', verbose_name='allow recurrence'),
        ),
    ]
