# Generated by Django 3.0 on 2020-04-06 19:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Chat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('first', models.ForeignKey(help_text='The first user in the chat', on_delete=django.db.models.deletion.CASCADE, related_name='chat_first', to=settings.AUTH_USER_MODEL, verbose_name='first user')),
                ('second', models.ForeignKey(help_text='The second user in the chat', on_delete=django.db.models.deletion.CASCADE, related_name='chat_second', to=settings.AUTH_USER_MODEL, verbose_name='second user')),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(help_text='Message content', verbose_name='message')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('chat', models.ForeignKey(help_text='The message that was sent', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='chat', to='communication.Chat', verbose_name='chat')),
                ('user', models.ForeignKey(help_text='The user that sent the message', on_delete=django.db.models.deletion.CASCADE, related_name='chat_messages', to=settings.AUTH_USER_MODEL, verbose_name='sender')),
            ],
        ),
    ]
