# Generated by Django 3.0 on 2020-06-02 16:25

import content.model_exts
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('administration', '0052_auto_20200602_1123'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ArtistOfTheWeek',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('promotion_ideas', models.TextField(blank=True, null=True, verbose_name='promotion ideas')),
                ('picture', models.FileField(blank=True, null=True, upload_to=content.model_exts.custom_image_upload, verbose_name='picture')),
                ('facebook_link', models.CharField(blank=True, max_length=255, null=True, verbose_name='Facebook link')),
                ('instagram_handle', models.CharField(blank=True, max_length=255, null=True, verbose_name='Instagram handle')),
                ('soundcloud_link', models.CharField(blank=True, max_length=255, null=True, verbose_name='Soundcloud link')),
                ('spotify_link', models.CharField(blank=True, max_length=255, null=True, verbose_name='Spotify link')),
                ('youtube_link', models.CharField(blank=True, max_length=255, null=True, verbose_name='Youtube link')),
                ('other_link_description_1', models.CharField(blank=True, max_length=255, null=True, verbose_name='other link description 1')),
                ('other_link_1', models.CharField(blank=True, max_length=255, null=True, verbose_name='other link 1')),
                ('other_link_description_2', models.CharField(blank=True, max_length=255, null=True, verbose_name='other link description 2')),
                ('other_link_2', models.CharField(blank=True, max_length=255, null=True, verbose_name='other link 2')),
                ('other_link_description_3', models.CharField(blank=True, max_length=255, null=True, verbose_name='other link description 3')),
                ('other_link_3', models.CharField(blank=True, max_length=255, null=True, verbose_name='other link 3')),
                ('seen', models.BooleanField(default=False, help_text='Mark if the application has been seen by a member of the Revibe team.', verbose_name='seen')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('denied', 'Denied'), ('complete', 'Completed')], default='pending', help_text='Application status', max_length=50, verbose_name='status')),
                ('post', models.ForeignKey(blank=True, help_text='The blog post that was written from this application', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='application', to='administration.Blog', verbose_name='blog post')),
                ('user', models.ForeignKey(blank=True, help_text='The user that submitted the application', limit_choices_to=models.Q(('is_artist', True), ('artist__isnull', False), _connector='OR'), null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='artistoftheweek_applications', to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
            options={
                'verbose_name': 'artist of the week',
                'verbose_name_plural': 'artists of the week',
            },
        ),
    ]
