# Generated by Django 3.0 on 2020-06-02 16:45

from django.db import migrations, models
import surveys.utils.models


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='artistoftheweek',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='artistoftheweek',
            name='last_changed',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='artistoftheweek',
            name='staff_notes',
            field=models.TextField(blank=True, null=True, verbose_name='staff notes'),
        ),
        migrations.AlterField(
            model_name='artistoftheweek',
            name='picture',
            field=models.FileField(blank=True, null=True, upload_to=surveys.utils.models.custom_file_upload, verbose_name='picture'),
        ),
    ]
