# Generated by Django 3.0 on 2020-06-02 16:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0052_auto_20200602_1123'),
        ('surveys', '0002_auto_20200602_1145'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artistoftheweek',
            name='post',
            field=models.ForeignKey(blank=True, help_text='The blog post that was written from this application', limit_choices_to={'category': 'artist_of_the_week'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='application', to='administration.Blog', verbose_name='blog post'),
        ),
    ]
