# Generated by Django 3.0 on 2020-06-17 02:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0003_auto_20200602_1146'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first', models.CharField(blank=True, default='', max_length=100, verbose_name='first name')),
                ('last', models.CharField(blank=True, default='', max_length=100, verbose_name='last name')),
                ('email', models.EmailField(blank=True, default='', max_length=250, verbose_name='contact email')),
                ('subject', models.CharField(blank=True, default='', max_length=250, verbose_name='contact subject')),
                ('message', models.TextField(verbose_name='contact message')),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='date and time')),
            ],
        ),
    ]
