# Generated by Django 3.0 on 2020-03-23 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0017_auto_20200320_1618'),
        ('cloud_storage', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='shared_with',
            field=models.ManyToManyField(help_text='Artists that have edit access to the file', related_name='shared_files', through='cloud_storage.FileShare', to='content.Artist', verbose_name='shared with'),
        ),
    ]
