# Generated by Django 3.0 on 2020-03-23 19:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cloud_storage', '0003_file_file_type'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='fileshare',
            options={'verbose_name': 'shared file', 'verbose_name_plural': 'shared files'},
        ),
    ]
