# Generated by Django 3.0 on 2020-03-25 20:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0018_auto_20200323_1458'),
        ('cloud_storage', '0004_auto_20200323_1458'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fileshare',
            name='artist',
            field=models.ForeignKey(help_text='The Artist the file is shared with', limit_choices_to={'platform': 'Revibe'}, on_delete=django.db.models.deletion.CASCADE, related_name='file_shares', to='content.Artist', verbose_name='artist'),
        ),
    ]
