# Generated by Django 2.2.6 on 2019-10-21 15:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0002_album_artist'),
    ]

    operations = [
        migrations.RenameField(
            model_name='song',
            old_name='name',
            new_name='title',
        ),
    ]
