# Generated by Django 2.2.6 on 2019-10-21 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0003_auto_20191021_1038'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to='album_image'),
        ),
    ]
