# Generated by Django 3.0 on 2020-01-22 19:50

import content.model_exts
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Track',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(blank=True, help_text='The audio file itself', null=True, upload_to=content.model_exts.custom_audio_upload)),
                ('reference', models.CharField(blank=True, help_text='Reference to the song location if it is not a revibe song', max_length=255, null=True)),
                ('is_original', models.BooleanField(blank=True, default=True, help_text='Shows if the uploaded file is the original file uploaded by the user')),
                ('song', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='content.Song')),
            ],
            options={
                'verbose_name': 'track',
                'verbose_name_plural': 'tracks',
            },
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(blank=True, default=None, help_text='The file that will be uploaded / is uploaded in S3', null=True, upload_to=content.model_exts.custom_image_upload)),
                ('reference', models.CharField(blank=True, default=None, help_text='Reference to the file location if it is not a revibe image', max_length=255, null=True)),
                ('height', models.IntegerField()),
                ('width', models.IntegerField()),
                ('is_original', models.BooleanField(blank=True, default=True, help_text='Shows if the uploaded file is the original file uploaded by the user')),
                ('album', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='album_image', to='content.Album')),
                ('artist', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='artist_image', to='content.Artist')),
            ],
            options={
                'verbose_name': 'image',
                'verbose_name_plural': 'images',
            },
        ),
    ]
