# Generated by Django 3.0 on 2019-12-18 15:39

import content.model_exts
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Image',
        ),
        migrations.AddField(
            model_name='album',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to=content.model_exts.rename_image),
        ),
        migrations.AddField(
            model_name='artist',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to=content.model_exts.rename_image),
        ),
        migrations.AlterField(
            model_name='artist',
            name='name',
            field=models.CharField(max_length=255),
        ),
    ]
