# Generated by Django 3.0 on 2019-12-21 20:31

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0003_auto_20191218_1105'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='album',
            managers=[
                ('display_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='song',
            managers=[
                ('display_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='songcontributor',
            managers=[
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
    ]
