# Generated by Django 3.0 on 2020-02-03 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0003_auto_20200123_0925'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='is_deleted',
            field=models.BooleanField(blank=True, default=False, verbose_name='deletion status'),
        ),
        migrations.AlterField(
            model_name='album',
            name='is_displayed',
            field=models.BooleanField(blank=True, default=True, verbose_name='display status'),
        ),
        migrations.AlterField(
            model_name='albumcontributor',
            name='primary_artist',
            field=models.BooleanField(blank=True, default=False, verbose_name='primary artist status'),
        ),
        migrations.AlterField(
            model_name='image',
            name='is_original',
            field=models.BooleanField(blank=True, default=True, help_text='Shows if the uploaded file is the original file uploaded by the user', verbose_name='original file status'),
        ),
        migrations.AlterField(
            model_name='song',
            name='is_deleted',
            field=models.BooleanField(blank=True, default=False, verbose_name='deletion status'),
        ),
        migrations.AlterField(
            model_name='song',
            name='is_displayed',
            field=models.BooleanField(blank=True, default=True, verbose_name='display status'),
        ),
        migrations.AlterField(
            model_name='songcontributor',
            name='primary_artist',
            field=models.BooleanField(blank=True, default=False, verbose_name='primary artist status'),
        ),
        migrations.AlterField(
            model_name='track',
            name='is_original',
            field=models.BooleanField(blank=True, default=True, help_text='Shows if the uploaded file is the original file uploaded by the user', verbose_name='original file status'),
        ),
    ]
