# Generated by Django 3.0 on 2020-02-05 17:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0004_auto_20200203_0907'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='album',
            options={'ordering': ['name'], 'verbose_name': 'album', 'verbose_name_plural': 'albums'},
        ),
    ]
