# Generated by Django 3.0 on 2019-12-21 23:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0004_auto_20191221_1431'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='album',
            managers=[
            ],
        ),
        migrations.AlterModelManagers(
            name='song',
            managers=[
            ],
        ),
        migrations.AlterModelManagers(
            name='songcontributor',
            managers=[
            ],
        ),
    ]
