# Generated by Django 3.0 on 2019-12-23 01:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0005_auto_20191221_1729'),
    ]

    operations = [
        migrations.AddField(
            model_name='artist',
            name='image_reference',
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),
    ]
