# Generated by Django 3.0 on 2019-12-23 02:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0006_artist_image_reference'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='image_ref',
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),
    ]
