# Generated by Django 3.0 on 2019-12-28 18:49

from django.db import migrations, models

from datetime import datetime

def datetime_to_date(apps, schema_editor):
    Album = apps.get_model('content','Album')
    for album in Album.objects.all():
        if album.uploaded_date:
            album.uploaded_date = datetime.date(album.uploaded_date)
            album.save()
        if album.last_changed:
            album.last_changed = datetime.date(album.last_changed)
            album.save()

class Migration(migrations.Migration):

    dependencies = [
        ('content', '0007_album_image_ref'),
    ]

    operations = [
        # migrations.RemoveField(
        #     model_name='album',
        #     name='date_added',
        # ),
        # migrations.AddField(
        #     model_name='album',
        #     name='uploaded_date',
        #     field=models.DateField(auto_now_add=True, null=True),
        # ),
        migrations.RenameField(
            model_name='album',
            old_name='date_added',
            new_name='uploaded_date',
        ),
        migrations.AlterField(
            model_name='album',
            name='last_changed',
            field=models.DateField(auto_now=True, null=True),
        ),
        migrations.RunPython(datetime_to_date),
    ]
