# Generated by Django 3.0 on 2019-12-28 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0008_auto_20191228_1249'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='uploaded_date',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
