# Generated by Django 3.0 on 2020-02-18 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0009_auto_20200218_1124'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='tags',
            field=models.ManyToManyField(blank=True, help_text='Associated tags', related_name='albums', to='content.Tag'),
        ),
        migrations.AlterField(
            model_name='song',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='songs', to='content.Tag'),
        ),
    ]
