# Generated by Django 3.0 on 2019-12-31 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0009_auto_20191228_1310'),
    ]

    operations = [
        migrations.AddField(
            model_name='artist',
            name='date_joined',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
