# Generated by Django 3.0 on 2020-01-01 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0010_artist_date_joined'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artist',
            name='date_joined',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
