# Generated by Django 3.0 on 2020-02-24 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0011_auto_20200224_1318'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='streams_last_month',
            field=models.IntegerField(blank=True, default=0, help_text='Number of streams recorded in DynamoDB in the last 30 days. Will be updated automatically.', verbose_name='streams in the last 30 days'),
        ),
        migrations.AlterField(
            model_name='song',
            name='streams_this_year',
            field=models.IntegerField(blank=True, default=0, help_text='Number of streams recorded in DynamoDB during this calendar year. Will be updated automatically.', verbose_name='streams this calendar year'),
        ),
    ]
