# Generated by Django 3.0 on 2020-02-25 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0012_auto_20200224_1318'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='streams_all_time',
            field=models.IntegerField(blank=True, default=0, help_text='Number of streams recorded in DynamoDB all time. Will be updated automatically.', verbose_name='streams all time'),
        ),
    ]
