# Generated by Django 3.0 on 2020-03-18 16:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0014_auto_20200226_1026'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlaceholderContribution',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(help_text='If an artist registers with this email, then will automatically create the contributions', max_length=255, verbose_name='email')),
                ('contribution_type', models.CharField(help_text='the contribution type to be applied when creating the contribution', max_length=255, verbose_name='contribution type')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('song', models.ForeignKey(help_text='The related song', on_delete=django.db.models.deletion.CASCADE, related_name='placeholder_contributions', to='content.Song', verbose_name='song')),
            ],
            options={
                'verbose_name': 'placeholder contribution',
                'verbose_name_plural': 'placeholder contributions',
            },
        ),
    ]
