# Generated by Django 3.0 on 2020-03-23 19:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0017_auto_20200320_1618'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='good',
        ),
        migrations.RemoveField(
            model_name='track',
            name='good',
        ),
    ]
