# Generated by Django 3.0 on 2020-04-20 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0019_auto_20200330_1100'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='album_order',
            field=models.IntegerField(blank=True, default=0, help_text='The order in which the songs will be displayed in the app.', verbose_name='order'),
        ),
    ]
