# Generated by Django 3.0 on 2020-04-28 17:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0022_auto_20200422_0930'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='genre',
            options={'verbose_name': 'genre', 'verbose_name_plural': 'genres'},
        ),
    ]
