# Generated by Django 3.0 on 2020-05-22 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0025_auto_20200522_1158'),
    ]

    operations = [
        migrations.AddField(
            model_name='artist',
            name='last_changed',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
