# Generated by Django 3.0 on 2020-05-26 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0027_albumsearch_artistsearch_genresearch_search_songsearch_tagsearch'),
    ]

    operations = [
        migrations.AddField(
            model_name='search',
            name='order',
            field=models.IntegerField(default=0, help_text='Order in which to execute the search function', verbose_name='order'),
            preserve_default=False,
        ),
    ]
