# Generated by Django 3.0 on 2020-06-10 17:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0053_artistoftheweek'),
        ('content', '0028_search_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='artistoftheweek',
            field=models.ForeignKey(blank=True, help_text='Artist of the Week related object', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='images', to='administration.ArtistOfTheWeek', verbose_name='artist of the week'),
        ),
    ]
