# Generated by Django 3.0 on 2020-05-07 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='trigger',
            field=models.CharField(default='-', help_text='Action that triggers the notification to be sent', max_length=255, verbose_name='trigger'),
            preserve_default=False,
        ),
    ]
