# Generated by Django 3.0 on 2020-05-07 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_event_trigger'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='trigger_delay',
            field=models.DurationField(blank=True, help_text='Time delay on sending the notification after the trigger is activated.', null=True, verbose_name='trigger delay'),
        ),
    ]
