# Generated by Django 3.0 on 2020-05-07 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0003_event_trigger_delay'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='trigger_delay',
            field=models.DurationField(blank=True, help_text="Time delay on sending the notification after the trigger is activated. Use the format '[DD] [[hh:]mm:]ss'.", null=True, verbose_name='trigger delay'),
        ),
    ]
