# Generated by Django 3.0 on 2020-05-07 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0004_auto_20200507_1000'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reminder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of the reminder', max_length=255, unique=True, verbose_name='name')),
                ('desired_action', models.CharField(help_text='ACtion the user is desired to take after receiving this reminder', max_length=255, verbose_name='desired action')),
                ('automation_order', models.IntegerField(blank=True, help_text='Order in the automation stack that this reminder will be executed', null=True, unique=True, verbose_name='automation order')),
                ('description', models.TextField(help_text='Text explanation of the reminder', verbose_name='description')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('last_changed', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
