# Generated by Django 3.0 on 2020-05-07 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0005_reminder'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reminder',
            options={'verbose_name': 'reminder', 'verbose_name_plural': 'reminders'},
        ),
        migrations.AddField(
            model_name='reminder',
            name='active',
            field=models.BooleanField(blank=True, default=True, help_text='The reminder is active and will send notifications. Please set this to False rather than deleting the object; deleting the object will inhibit analysis.', verbose_name='active'),
        ),
        migrations.AddField(
            model_name='reminder',
            name='for_artists',
            field=models.BooleanField(default=False, help_text='This notification is for artists, not listeners.', verbose_name='for artists'),
            preserve_default=False,
        ),
    ]
