# Generated by Django 3.0 on 2020-05-08 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0007_notification_seen'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notificationtemplate',
            name='html',
        ),
        migrations.RemoveField(
            model_name='notificationtemplate',
            name='text_template',
        ),
        migrations.AddField(
            model_name='notificationtemplate',
            name='active',
            field=models.BooleanField(blank=True, default=True, help_text='The template is active and will be used for notifications', verbose_name='active'),
        ),
        migrations.AddField(
            model_name='notificationtemplate',
            name='body',
            field=models.TextField(default='email', help_text='The format-string message to send to the user. If this is an email template, paste the HTML here.', verbose_name='body'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='notificationtemplate',
            name='medium',
            field=models.CharField(choices=[('email', 'Email'), ('in_app', 'In-App'), ('push', 'Push'), ('sms', 'Text Message')], default='email', help_text='The medium by which to send the notification', max_length=255, verbose_name='medium'),
            preserve_default=False,
        ),
    ]
