# Generated by Django 3.0 on 2020-05-08 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0009_event_sent_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='notificationtemplate',
            name='subject',
            field=models.TextField(blank=True, help_text='Notification subject. If sending an email message this field CANNOT be blank!', null=True, verbose_name='subject'),
        ),
    ]
