# Generated by Django 3.0 on 2020-05-08 17:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0010_notificationtemplate_subject'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Reminder',
        ),
    ]
