# Generated by Django 3.0 on 2020-05-20 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0012_auto_20200514_1057'),
    ]

    operations = [
        migrations.CreateModel(
            name='TemporalEvent',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('notifications.event',),
        ),
        migrations.AddField(
            model_name='event',
            name='type',
            field=models.CharField(choices=[('external', 'External'), ('temporal', 'Temporal')], default='external', help_text='The type of Event this is', max_length=100, verbose_name='type'),
        ),
    ]
