# Generated by Django 3.0 on 2020-05-20 16:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0013_auto_20200520_1137'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExternalEvent',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('notifications.event',),
        ),
    ]
