# Generated by Django 3.0 on 2020-05-21 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0014_externalevent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='last_changed',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
