# Generated by Django 3.0 on 2020-05-27 16:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0015_auto_20200521_1245'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='desired_action',
        ),
        migrations.RemoveField(
            model_name='event',
            name='trigger_delay',
        ),
    ]
