# Generated by Django 3.0 on 2020-06-08 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0016_auto_20200527_1134'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='required_request_body',
            field=models.TextField(default='{}', help_text='Keyward arguments that must evaluate to True when checked against the request body', verbose_name='request body'),
        ),
        migrations.AddField(
            model_name='event',
            name='required_request_headers',
            field=models.TextField(default='{}', help_text='Keyward arguments that must evaluate to True when checked against the request headers', verbose_name='request headers'),
        ),
        migrations.AddField(
            model_name='event',
            name='required_request_params',
            field=models.TextField(default='{}', help_text='Keyward arguments that must evaluate to True when checked against the request parameters', verbose_name='request params'),
        ),
        migrations.AddField(
            model_name='event',
            name='required_response_body',
            field=models.TextField(default='{}', help_text='Keyward arguments that must evaluate to True when checked against the response body', verbose_name='response body'),
        ),
    ]
