# Generated by Django 3.0 on 2020-06-10 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0017_auto_20200608_1206'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='read_id',
            field=models.UUIDField(blank=True, help_text='ID to use for tracking the notification', null=True, verbose_name='read id'),
        ),
    ]
