# Generated by Django 3.0 on 2020-06-10 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0018_notification_read_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='date_seen',
            field=models.DateTimeField(blank=True, help_text='When the notification was seen', null=True, verbose_name='date seen'),
        ),
    ]
