# Generated by Django 3.0 on 2020-06-17 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0020_auto_20200615_1511'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='notificationtemplate',
            options={'verbose_name': 'template', 'verbose_name_plural': 'templates'},
        ),
        migrations.AlterField(
            model_name='notificationtemplate',
            name='branch_campaign',
            field=models.CharField(blank=True, help_text="Branch campaign field. Defaults to Event's 'name' field.", max_length=255, null=True, verbose_name='campaign'),
        ),
        migrations.AlterField(
            model_name='notificationtemplate',
            name='branch_channel',
            field=models.CharField(blank=True, help_text="Branch channel/source. Defaults to the Event's type (External/Temporal).", max_length=255, null=True, verbose_name='channel'),
        ),
        migrations.AlterField(
            model_name='notificationtemplate',
            name='branch_tags',
            field=models.TextField(blank=True, help_text='Comma-separated tags for branch links. Will be null if left blank.', null=True, verbose_name='tags'),
        ),
    ]
