# Generated by Django 3.0 on 2020-06-18 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0022_auto_20200617_1511'),
    ]

    operations = [
        migrations.AddField(
            model_name='notificationtemplate',
            name='render_version',
            field=models.CharField(blank=True, choices=[('v1', 'Simply Python Rendering (V1)'), ('v2', 'Django Template Rendering (V2)')], default='v2', help_text='Version of HTML rendering to use when formatting the message.', max_length=255, verbose_name='render version'),
        ),
    ]
