# Generated by Django 2.2.6 on 2019-10-30 19:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Album',
            fields=[
                ('album_id', models.AutoField(primary_key=True, serialize=False)),
                ('album_name', models.CharField(max_length=255)),
                ('album_image', models.FileField(upload_to='image/albums', verbose_name='Album Image')),
            ],
        ),
        migrations.CreateModel(
            name='Artist',
            fields=[
                ('artist_id', models.AutoField(primary_key=True, serialize=False)),
                ('artist_name', models.CharField(max_length=255, verbose_name='Display Name')),
                ('artist_image', models.FileField(upload_to='images/artists', verbose_name='Display Image')),
                ('platform', models.CharField(max_length=255)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Song',
            fields=[
                ('song_id', models.AutoField(primary_key=True, serialize=False)),
                ('song_file', models.FileField(upload_to='audio/songs', verbose_name='Song')),
                ('song_title', models.CharField(max_length=255, verbose_name='Title')),
                ('duration', models.DurationField(verbose_name='Duration')),
                ('url', models.URLField(verbose_name='URL')),
                ('platform', models.CharField(max_length=255)),
                ('uploaded_date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='SongContributors',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contribution_type', models.CharField(max_length=255)),
                ('artist_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='newModelTesting.Artist')),
                ('song_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='newModelTesting.Song')),
            ],
        ),
        migrations.AddField(
            model_name='song',
            name='contributors',
            field=models.ManyToManyField(related_name='song_contributors', through='newModelTesting.SongContributors', to='newModelTesting.Artist'),
        ),
        migrations.AddField(
            model_name='song',
            name='uploaded_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='song_uploaded_by', to='newModelTesting.Artist'),
        ),
        migrations.CreateModel(
            name='Social',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paltform', models.CharField(max_length=255)),
                ('user_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=255, verbose_name='First Name')),
                ('last_name', models.CharField(max_length=255, verbose_name='First Name')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('profile_picture', models.FileField(upload_to='images/profiles', verbose_name='Profile Picture')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Playlist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('song_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='newModelTesting.Song')),
                ('user_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Library',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(max_length=255)),
                ('song_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='newModelTesting.Song')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='AlbumContributors',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contribution_type', models.CharField(max_length=255)),
                ('album_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='newModelTesting.Album')),
                ('artist_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='newModelTesting.Artist')),
            ],
        ),
        migrations.AddField(
            model_name='album',
            name='contributors',
            field=models.ManyToManyField(through='newModelTesting.AlbumContributors', to='newModelTesting.Artist'),
        ),
    ]
