# Generated by Django 2.2.6 on 2019-10-31 20:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('newModelTesting', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='artist',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='artist_user', to='newModelTesting.Artist'),
        ),
    ]
