# Generated by Django 2.2.6 on 2019-10-31 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newModelTesting', '0002_auto_20191031_1554'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='email',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='last_name',
        ),
        migrations.AddField(
            model_name='profile',
            name='country',
            field=models.CharField(max_length=255, null=True, verbose_name='Country'),
        ),
        migrations.AddField(
            model_name='profile',
            name='dob',
            field=models.DateField(null=True, verbose_name='Date of Birth'),
        ),
        migrations.AlterField(
            model_name='album',
            name='image',
            field=models.FileField(null=True, upload_to='image/albums', verbose_name='Album Image'),
        ),
        migrations.AlterField(
            model_name='albumcontributors',
            name='contribution_type',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='library',
            name='platform',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='social',
            name='paltform',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='song',
            name='duration',
            field=models.IntegerField(null=True, verbose_name='Duration'),
        ),
        migrations.AlterField(
            model_name='song',
            name='platform',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='song',
            name='uploaded_date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='songcontributors',
            name='contribution_type',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
