# Generated by Django 2.2.6 on 2019-11-01 16:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('revibe_api', '0002_auto_20191101_1140'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artist',
            name='manager',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='artist_manager', to=settings.AUTH_USER_MODEL),
        ),
    ]
