# Generated by Django 2.2.6 on 2019-11-01 16:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('revibe_api', '0003_auto_20191101_1147'),
    ]

    operations = [
        migrations.AddField(
            model_name='artist',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='artist_user', to=settings.AUTH_USER_MODEL),
        ),
    ]
